### ISSUE TITLE
Erreur de téléchargement d'images sur le wiki anglo

### ISSUE THREAD

**Issue by isabvllv** [LeHubca/lehub-mediawiki#11]
Les photos ne se téléchargent pas sur le Wiki anglo : https://en.wiki.lehub.ca/index.php/Main_Page (que ce soit avec l'extension Tiny MCE ou avec la page spéciale "Upload Files" (https://en.wiki.lehub.ca/index.php/Special:Upload) 

![upload file error wiki anglo](https://user-images.githubusercontent.com/92812140/167303854-a1aa6073-850b-4d61-9c66-045d7ebae045.PNG)
![wiki bug](https://user-images.githubusercontent.com/92812140/167303853-e8e8813f-e39b-4ec6-86b4-0b1016333a82.png)
![wiki bug](https://user-images.githubusercontent.com/92812140/167303855-ce1e8946-8fc4-42fa-a474-109cc73c8aed.png)
![upload file error wiki anglo](https://user-images.githubusercontent.com/92812140/167303856-812002f5-1e3f-4eaa-88c4-5f3207ce0bd6.PNG)

Lien dans la capture d'écran : https://www.mediawiki.org/wiki/Manual:$wgUploadDirectory

**Comment by alberto56** [comment]
Salut,

J'ai fait une modifications aux permissions de fichiers:

    chown -R www-data:www-data images

Sur le conteneur.

J'ai ensuite réussi à téléverser des images sur le wiki franco et anglo:

* https://fr.wiki.lehub.ca/index.php/Fichier:Badge_shared_badge.png
* https://en.wiki.lehub.ca/index.php/File:Badge_shared_badge.png
