### ISSUE TITLE
Had to restore from a backup, 6 hours or changes might be unavailable between 2022-12-16 6am and noon Eastern time

### ISSUE THREAD

**Issue by alberto56** [LeHubca/lehub-mediawiki#14]
Hi, 

https://en.wiki.lehub.ca/index.php/Main_Page is currently down and I'm working on a fix

https://fr.wiki.lehub.ca/index.php/Accueil is still up

**Comment by alberto56** [comment]
A regular upgraded caused a corruption of some data so I had to restore from a backup from this morning (6am on 2022-12-16), which means that **any changes made since 6am on 2022-12-16 might not appear on the site**.

I did take a backup of data just before the restore, so we have not lost anything, and I'll keep it for some time. 

Please comment on this issue if:

(1) https://en.wiki.lehub.ca/index.php/Main_Page is not working as expected
(2) https://fr.wiki.lehub.ca/index.php/Accueil is not working as expected
(3) you need any data from me for changes between 6am and noon on 2022-12-16 which are currently not appearing on either the FR or EN sites.

**Comment by isabvllv** [comment]
everything seems to be there and work, thank you for the update Albert !:)

**Comment by alberto56** [comment]
Thanks, closing.
