### ISSUE TITLE
Installation de Embed-Video et Visual Editor

### ISSUE THREAD

**Issue by alberto56** [LeHubca/lehub-mediawiki#2]
[Ceci est fait](https://github.com/LeHubca/lehub-mediawiki/blob/833aff2aac04cd066e683cf2e6eff2c6ab494a1d/Dockerfile#L16-L28).

SVP tester et fermer si ticket si tout fonctionne.

**Comment by isabvllv** [comment]
![Capture](https://user-images.githubusercontent.com/92812140/141486414-8de49e12-67bc-4028-ab02-69a8c2a70a6d.PNG)
*Seulement sur la page principale* : lorsque je clique sur Edit, l'extension ne fonctionne pas. Il apparaît un message d'erreur. @alberto56

**Comment by isabvllv** [comment]
*Sur les nouvelles pages que je crée* : l'extension fonctionne ! :)
![Capture2](https://user-images.githubusercontent.com/92812140/141491977-da3ea020-f85f-448c-9312-a0bcbd36d00e.PNG)
@alberto56

**Comment by isabvllv** [comment]
**Erreur sauvegarde d'une page créée avec l'extension** après avoir cliqué sur "Save Page"
![erreur sauvegarde](https://user-images.githubusercontent.com/92812140/141496557-f9751b08-ce99-4fe9-a8d5-4e000a97bfad.PNG)
@alberto56

**Comment by alberto56** [comment]
SVP fournir un scénario, étape par étape, pour obtenir cette erreur.

* Je vais au http://67.205.187.95:8080/index.php
* Je clique sur "Save changes"
* Je ne vois pas d'erreur

Que dois-je faire exactement pour voir cette erreur?

**Comment by isabvllv** [comment]
@alberto56 
MESSAGE D'ERREUR 1 : 
1. Aller au http://67.205.187.95:8080/index.php
2. Cliquer sur "Edit" en haut à droite
3.  Message d'erreur

MESSAGE D'ERREUR 2
1. Aller au http://67.205.187.95:8080/index.php?title=Perspective_anti-oppressive&action=edit&redlink=1 (une nouvelle page, peut importe laquelle)
2. Cliquer sur "Create" en haut à droite
3. Modifier la page, par exemple en écrivant "abcd" dans l'espace du texte principal.
4. Cliquer sur "Save Page..." en haut à droite.
5. Recliquer sur "Save page"
6.  Message d'erreur

**Comment by alberto56** [comment]
J'ai réussi à reproduire l'erreur. Je pense que c'est relié à Visual Editor.

Quelques ressources: 

* https://stackoverflow.com/questions/54656449/mediawiki-visualeditor-extension-curl-error-28-timeout-was-reached
* relié peut-être à https://www.mediawiki.org/wiki/Parsoid

Puisqu'il est possible d'éditer en mode "Edit source", je propose de regarder ça autour de mi-décembre.

**Comment by isabvllv** [comment]
Pas de problème! Je me concentrerai sur le contenu écrit simple avec un peu de short-code en attendant.

**Comment by isabvllv** [comment]
Bonjour Albert, as-tu eu le temps de creuser davantage la situation?

**Comment by alberto56** [comment]
Salut @isabvllv je n'ai pas trouvé de raison évidente (facilement réparable) pour ça. J'ai une rencontre avec Tom la semaine prochaine, je vais voir avec lui combien de temps j'aurai pour travailler là-dessus. À cette fin, j'aimerais savoir si c'est quelque chose qui te bloque, ou si tu peux continuer avec le short code s'il s'avère trop long à régler.

**Comment by alberto56** [comment]
Salut @isabvllv 

J'ai utilisé TinyMCE au lieu de VisualEditor, j'espère que ça pourra nous faire avancer.

Je n'arrive simplement pas à installer VisualEditor, j'ai documenté mon problème au https://stackoverflow.com/questions/70808368.

Toutefois j'espère que TinyMCE fonctionnera pour vos besoins:

Tu peux voir les résultats au http://67.205.187.95:8080/index.php?title=Wiki-militant&action=tinymceedit

**Important: quand on crée de nouvelles pages, il n'y a pas de WYSIWYG. Il faut enregistrer la page, et ensuite faire Edit, et là ça fonctionnera.**

ça ressemble à ça:

<img width="1369" alt="Screen Shot 2022-01-21 at 5 41 53 PM" src="https://user-images.githubusercontent.com/808265/150609791-c131b7a8-6c15-4342-9efe-3b52eaf75d0b.png">

SVP me dire si ça marche.

**Comment by isabvllv** [comment]
Ça fonctionne merci! La seule chose problématique est le short-code en lien avec Embed-Video qui ne fait plus apparaître les vidéos. Tu peux voir un exemple à cette adresse : http://67.205.187.95:8080/index.php/Reconnaissance_du_territoire.
Avant, avec le même short-code soit :  {{#evu:https://www.youtube.com/watch?v=5Mm2vDSgXD0 |alignment=center }}, un vidéo apparaissait sur la page.

**Comment by alberto56** [comment]
Il semble que j'avais enlevé la ligne qui installait embed-video. Je l'ai remise ici: https://github.com/LeHubca/lehub-mediawiki/commit/4426dfc92ee3d4db17f009ad750df82a0ec687a5

Ça semble fonctionner: http://67.205.187.95:8080/index.php/Reconnaissance_du_territoire

**Comment by isabvllv** [comment]
#`close`
