### ISSUE TITLE
Switch franco wiki system language to french

### ISSUE THREAD

**Issue by tliacas** [LeHubca/lehub-mediawiki#3]
To be clear, this is only for the wiki here:
http://67.205.187.95:8080/index.php/Wiki-militant

Here is a guide for how to do this via hosting admin panel:
https://www.inmotionhosting.com/support/edu/mediawiki/change-interface-language-media/

**Comment by alberto56** [comment]
This is pending #4

**Comment by alberto56** [comment]
This should now be ok:
<img width="514" alt="Screen Shot 2022-02-03 at 2 53 09 PM" src="https://user-images.githubusercontent.com/808265/152418576-64ecc14a-4e6b-45fc-bf89-d02dc946521f.png">
<img width="658" alt="Screen Shot 2022-02-03 at 2 53 21 PM" src="https://user-images.githubusercontent.com/808265/152418579-819c2d40-5620-4b4b-a9d2-d16d065f024d.png">

**Comment by alberto56** [comment]
This is now working in my tests, I will close, please reopen if needed.
