### ISSUE TITLE
Enlever la possibilité à des personnes externes de créer des pages Wiki

### ISSUE THREAD

**Issue by isabvllv** [LeHubca/lehub-mediawiki#5]
Bonjour Albert,

N'importe qui peut présentement créer une page Wiki sur  https://fr.wiki.lehub.ca. 

1. Se connecter sur le wiki franco : https://fr.wiki.lehub.ca/index.php/Accueil pour voir des pages qui ont été créées par des utilisateurs  ou utilisateurs auto-confirmés.
 Liste des utilisateurs : https://fr.wiki.lehub.ca/index.php/Accueil
 Exemple de page créée  : https://fr.wiki.lehub.ca/index.php/All_Migrants_Living_In_UK_Eligible_For_COVID-19_Vaccine 

2. Enlever les droits des groupes (ou les effacer si nécessaire) qui ne sont pas des administrateurs. 

Documentation pertinente : https://www.mediawiki.org/wiki/Manual:User_rights et https://www.mediawiki.org/wiki/Help:User_rights_and_groups 

Si tu as des questions, n'hésite pas! :) Bonne journée!

**Comment by alberto56** [comment]
Basé sur https://www.mediawiki.org/wiki/Manual:Preventing_access, j'ai ajouté:

    # Disable anonymous editing
    $wgGroupPermissions['*']['edit'] = false;

    # Prevent new user registrations except by sysops
    $wgGroupPermissions['*']['createaccount'] = false;

fr.wiki.lehub.ca:/root/starterkit-mediawiki/LocalSettings.php
en.wiki.lehub.ca:/root/starterkit-mediawiki-en/LocalSettings.php

ssh root@fr.wiki.lehub.ca "cd /root/starterkit-mediawiki && ./scripts/deploy.sh"
ssh root@en.wiki.lehub.ca "cd /root/starterkit-mediawiki-en && ./scripts/deploy.sh"

En principe il devrait être impossible de créer des comptes maintenant. 

J'ai aussi bloqué les comptes existants et effacé les pages spam.

**Comment by isabvllv** [comment]
#`close`
