### ISSUE TITLE
Citations Tiny Mce

### ISSUE THREAD

**Issue by isabvllv** [LeHubca/lehub-mediawiki#6]
Salut Albert,

En vertu de la page Media Wiki associée à l'extension Tiny MCE (https://www.mediawiki.org/wiki/Extension:TinyMCE), celle-ci devrait comporter une option pour inclure des citations dans la barre d'outils. Or, ce n'est pas le cas. 

Ça serait utile d'avoir accès à une extension permettant d'inclure des "notes de bas de page", que ce soit via Tiny MCE ou grâce à l'extension Cite ( https://www.mediawiki.org/wiki/Extension:Cite). 

Je te souhaite une belle journée! :)

Isabelle

**Comment by alberto56** [comment]
Quand vous dites:

> En vertu de la page Media Wiki associée à l'extension Tiny MCE (https://www.mediawiki.org/wiki/Extension:TinyMCE), celle-ci devrait comporter une option pour inclure des citations dans la barre d'outils

SVP préciser le texte de cette page qui vous fait penser ça. J'ai fait une recherche pour "footnote" sur la page https://www.mediawiki.org/wiki/Extension:TinyMCE et je n'ai rien trouvé. 
<img width="773" alt="Screen Shot 2022-03-18 at 8 21 39 PM" src="https://user-images.githubusercontent.com/808265/159099185-851aa8a8-0e46-4f9b-a28d-9f98da6704ae.png">

**Comment by isabvllv** [comment]
![Capture](https://user-images.githubusercontent.com/92812140/159184716-13e8d1e6-90fc-4287-8802-4a428b229b33.PNG)

L'outil concerne plutôt les références plutôt que les notes de bas de page, mon erreur! Il n'est toutefois pas dispo sur le Wiki du HUB.

Disponible sur cette page : https://www.mediawiki.org/wiki/Extension:TinyMCE

**Comment by alberto56** [comment]
Je n'ai pas réussi à l'installer, mais j'ai ouvert une question sur Stackoverflow au https://stackoverflow.com/questions/71577367/in-mediawikis-tinymce-extension-how-to-enable-disable-buttons

**Comment by alberto56** [comment]
Toujours pas réussi, on essaie encore. J'ai écrit ce blog post sur ma progression là-dessus: https://blog.dcycle.com/blog/2022-04-22/mediawiki-customizing-tinymce/

**Comment by alberto56** [comment]
J'ai pu finalement ajouter le bouton. SVP tester.

<img width="1077" alt="Screen Shot 2022-04-26 at 4 11 13 PM" src="https://user-images.githubusercontent.com/808265/165384054-909ac758-2957-418d-83dc-f0370bfbcc0a.png">
