### ISSUE TITLE
Téléchargement PDF 

### ISSUE THREAD

**Issue by isabvllv** [LeHubca/lehub-mediawiki#7]
Bonjour Albert,  
il n'est actuellement pas possible de téléverser des documents PDF sur la plateforme. ( https://fr.wiki.lehub.ca/index.php/Sp%C3%A9cial:T%C3%A9l%C3%A9verser) 

Ces deux extensions permettent de le faire : https://www.mediawiki.org/wiki/Extension:PDFEmbed et  https://www.mediawiki.org/wiki/Extension:PdfHandler. Je te laisse voir laquelle serait compatible avec ce qu'on a actuellement. PDF Embed serait à préconiser si les deux sont compatibles.

**Comment by alberto56** [comment]
PDFEmbed n'a pas été mis à jour pour deux ans selon https://gitlab.com/hydrawiki/extensions/PDFEmbed mais https://github.com/wikimedia/mediawiki-extensions-PdfHandler est beaucoup plus activement développé, et fait partie de Wikimedia 1.21 selon https://www.mediawiki.org/wiki/Extension:PdfHandler donc je vais voir comment le configurer.

**Comment by alberto56** [comment]
SVP confirmer que votre intention est d'avoir un bouton ici qui vous permet de téléverser un PDF.

<img width="1490" alt="Screen Shot 2022-03-18 at 8 19 22 PM" src="https://user-images.githubusercontent.com/808265/159099061-a65d7ae4-859d-4022-900b-a3b0cc266573.png">

**Comment by isabvllv** [comment]
Bonjour @alberto56, oui c'est effectivement ça qui serait optimal!

**Comment by alberto56** [comment]
J'ai [permis le téléversement de documents PDF](https://github.com/LeHubca/lehub-mediawiki/commit/4be8fb450e22347fc3ae01a61fb1c54c29c80d22) et ensuite, au https://fr.wiki.lehub.ca/index.php/Issue-7, j'ai pu utiliser l'icône de l'image pour téléverser un PDF et ça fonctionner pour moi. 

<img width="594" alt="Screen Shot 2022-04-23 at 12 55 26 PM" src="https://user-images.githubusercontent.com/808265/164915868-3061bd2c-ef44-43f4-8817-76292d64f68c.png">

**Comment by isabvllv** [comment]
Oui ça fonctionne merci :)
