### ISSUE TITLE
Make image size responsive (to screen size)

### ISSUE THREAD

**Issue by isabvllv** [LeHubca/lehub-mediawiki#8]
Salut Albert, 

Sur Mediawiki, la largeur des tableaux s'ajuste automatiquement en fonction de l'écran utilisé, mais ce n'est pas le cas automatiquement pour les images. 

J'ai essayé d'appliquer les solutions proposées dans ces trois sources sans succès 

https://www.mediawiki.org/wiki/Topic:Tuubagqalz9vk2m9 
https://github.com/borkweb/BootstrapMediaWiki/issues/49 
https://stackoverflow.com/questions/9078157/is-there-a-way-automatically-to-resize-mediawiki-images-depending-on-screen-size 

Ce serait important de régler ce problème sans quoi la taille de l'image devient soit trop importante soit trop petite en fonction de l'écran. Le but est que celle-ci soit toujours à 100% de la largeur de l'écran.

**Comment by isabvllv** [comment]
Peut-être que cette extension permettrait d'y arriver : https://www.mediawiki.org/wiki/Extension:AdaptiveThumb

**Comment by alberto56** [comment]
J'ai créé une page au https://fr.wiki.lehub.ca/index.php/Issue-8 avec une petite image.

Ma compréhension de ce que tu demandes est que aimerais que cette image prenne toute la largeur de la page, c'est bien ça?

<img width="1190" alt="Screen Shot 2022-04-23 at 12 29 54 PM" src="https://user-images.githubusercontent.com/808265/164914823-31506c4d-7b26-4ab9-a880-aef1522137c2.png">

**Comment by isabvllv** [comment]
Bonjour @alberto56 , 
Donc voilà j'ai mis des exemples sur la page que tu as créée : https://fr.wiki.lehub.ca/index.php/Issue-8. Ce qu'on voudrait, c'est que les images se comportement comme les tableaux, c'est-à-dire que leur largeur s'adapte en fonction de l'écran qui ouvre la page. Comme tu le verras avec le premier exemple, si tu ouvres la page sur un ordinateur tout est beau, mais si tu vas sur la même page avec ton cellulaire, l'image est beaucoup trop large. Le tableau, quant à lui, est toujours d'une taille adapté à l'écran. C'est ce que je voulais dire par "responsive".  N'hésite pas si ce n'est toujours pas clair !

**Comment by alberto56** [comment]
@isabvllv SVP voir https://fr.wiki.lehub.ca/index.php/Issue-8

J'ai obetenu ce résultat en ajoutant du css au https://fr.wiki.lehub.ca/index.php?title=MediaWiki:Common.css&action=edit et https://en.wiki.lehub.ca/index.php?title=MediaWiki:Common.css&action=edit

SVP confirmer que c'est bien cela que vous cherchez

**Comment by isabvllv** [comment]
C'est parfait merci beaucoup Albert!
